UTS_DATA_MAINING

KASNA IMANUEL

2210111400270

JAWABAN TYPE DATA

In [ ]:

company_name_list = [{'name': 'Company 1'},
          {'name': 'Company 2'},
          {'name': 'Company 3'}]

employee_name_list = [{'name': 'John Doe'},
          {'name': 'Tom Smith'},
          {'name': 'Andrew Sebastian'}]

company_detail_list = {
      'Company 1': {
          'name': 'Company 1',
          'domain': 'Retail',
          'clients': [
              {
                  'name': 'acme.inc',
                  'country': 'united states'
              },
              {
                  'name': 'Wayne.co',
                  'country': 'united states'
              }
          ]
      },
      'Company 2': {
          'name': 'Company 2',
          'domain': 'Construction',
          'clients': [
              {
                  'name': 'Tesla',
                  'country': 'united states'
              },
              {
                  'name': 'Japan Airlines',
                  'country': 'japan'
              },
              {
                  'name': 'Indofood',
                  'country': 'indonesia'
              }
          ]
      },
      'Company 3': {
          'name': 'Company 3',
          'domain': 'Healthcare',
          'clients': [
              {
                  'name': 'Petronas',
                  'country': 'malaysia'
              },
              {
                  'name': 'VW Group',
                  'country': 'germany'
              },
              {
                  'name': 'IBM',
                  'country': 'united states'
              },
              {
                  'name': 'Mitsubishi',
                  'country': 'japan'
              }
          ]
      }
  }

employee_detail_list = {
      'John Doe': {
          'name': 'EMP-0001',
          'first_name': 'John',
          'last_name': 'Doe',
          'full_name': 'John Doe',
          'company': 'Company 1'
      },
      'Tom Smith': {
          'name': 'EMP-0002',
          'first_name': 'Tom',
          'last_name': 'Smith',
          'full_name': 'Tom Smith',
          'company': 'Company 2'
      },
      'Andrew Sebastian': {
          'name': 'EMP-0003',
          'first_name': 'Andrew',
          'last_name': 'Sebastian',
          'full_name': 'Andrew Sebastian',
          'company': 'Company 2'
      },
  }

Soal 1

In [149]:
def sort_company(company_list):
    for company_name, company_detail in company_detail_list.items():
        print("Name:", company_detail['name'])
        print("Domain:", company_detail['domain'])
        print()

company_detail_list = {
      'Company 1': {
          'name': 'Company 1',
          'domain': 'Retail'},
    'Company 2': {
          'name': 'Company 2',
          'domain': 'Construction'},
     'Company 3': {
          'name': 'Company 3',
          'domain': 'Healthcare'}}
     

   
sort_company(company_detail_list)

Name: Company 1
Domain: Retail

Name: Company 2
Domain: Construction

Name: Company 3
Domain: Healthcare



SOAL 2

In [154]:
def get_company_domain(company_detail_list):
    for company_name, details in company_detail_list.items():
        domain = details['domain']
        num_clients = len(details['clients'])
        print(f"{company_name}: {domain}, relation: {num_clients} clients")
get_company_domain(company_detail_list)

Company 1: Retail, relation: 2 clients
Company 2: Construction, relation: 3 clients
Company 3: Healthcare, relation: 4 clients


Soal 3

In [159]:
def print_employee_company_domain():
    for employee_name, employee_detail in employee_detail_list.items():
        company_name = employee_detail['company']
        company_domain = company_detail_list[company_name]['domain']
        full_name = employee_detail['full_name']
        print(f'"full_name": "{full_name}", "company": "{company_name}", "domain": "{company_domain}"')

# Memanggil fungsi untuk mencetak detail karyawan, perusahaan, dan domain
print_employee_company_domain()

"full_name": "John Doe", "company": "Company 1", "domain": "Retail"
"full_name": "Tom Smith", "company": "Company 2", "domain": "Construction"
"full_name": "Andrew Sebastian", "company": "Company 2", "domain": "Construction"


In [ ]:
SOAL 4

In [169]:
def get_employees_by_company():
 

  companies_with_employees = []
  for company_name, company_detail in company_detail_list.items():
    employees = [emp for emp, details in employee_detail_list.items() if details['company'] == company_name]
    company_info = {
      "company": company_name,
      "employees": employees
    }
    companies_with_employees.append(company_info)

  

  return companies_with_employees  # Optional, if you need the list returned


get_employees_by_company()


[{'company': 'Company 1', 'employees': ['John Doe']},
 {'company': 'Company 2', 'employees': ['Tom Smith', 'Andrew Sebastian']},
 {'company': 'Company 3', 'employees': []}]

PRE-PROCESING DATA

In [44]:
import pandas
import numpy
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer 

In [45]:
data_startups = pandas.read_csv('50_startups.csv')
data_startups.sample(7)

R&D Spend  Administration  Marketing Spend       State     Profit
23        NaN       105751.03              NaN     Florida  108733.99
38   20229.59        65947.93              NaN    New York   81229.06
24   77044.01             NaN        140574.81    New York  108552.04
39   38558.51        82982.09        174999.30  California   81005.76
0   165349.20       136897.80        471784.10    New York  192261.83
32   63408.86       129219.61         46085.25  California   97427.84
7   130298.13             NaN        323876.68     Florida  155752.60

1. Lakukan analisa mengenai field mana saja yang memiliki data kosong(Nan) lalu Isi data yang kosong tersebut menggunakan nilai mean

In [22]:
X = data_startups.sample(7).values
X

array([[91749.16, 114175.79, 294919.57, 'Florida', 124266.9],
       [78389.47, 153773.43, 299737.29, 'New York', 111313.02],
       [73994.56, 122782.75, 303319.26, 'Florida', 110352.25],
       [23640.93, 96189.63, 148001.11, 'California', 71498.49],
       [46014.02, 85047.44, 205517.64, 'New York', 96479.51],
       [119943.24, 156547.42, 256512.92, 'Florida', 132602.65],
       [162597.7, 151377.59, 443898.53, 'California', 191792.06]],
      dtype=object)

In [ ]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:])
X[:, 1:] = imputer.transform(X[:, 1:])

In [34]:
X

array([[1, 114175.79, 294919.57, 'Florida', 124266.9],
       [2, 153773.43, 299737.29, 'New York', 111313.02],
       [1, 122782.75, 303319.26, 'Florida', 110352.25],
       [0, 96189.63, 148001.11, 'California', 71498.49],
       [2, 85047.44, 205517.64, 'New York', 96479.51],
       [1, 156547.42, 256512.92, 'Florida', 132602.65],
       [0, 151377.59, 443898.53, 'California', 191792.06]], dtype=object)

In [38]:
label_encoder = LabelEncoder()
X[:, -2] =label_encoder.fit_transform(X[:,0])
X

array([[1, 114175.79, 294919.57, 1, 124266.9],
       [2, 153773.43, 299737.29, 2, 111313.02],
       [1, 122782.75, 303319.26, 1, 110352.25],
       [0, 96189.63, 148001.11, 0, 71498.49],
       [2, 85047.44, 205517.64, 2, 96479.51],
       [1, 156547.42, 256512.92, 1, 132602.65],
       [0, 151377.59, 443898.53, 0, 191792.06]], dtype=object)

2.Lakukan oneHotEncoder ke field state

In [43]:
one_hot_encoder = OneHotEncoder(categories=X[0])
ct = ColumnTransformer([("Datastartup", OneHotEncoder(),[0])], remainder="passthrough")
X = ct.fit_transform(X)
df = pandas.DataFrame(X)
df

0    1    2    3    4    5    6          7          8  9          10
0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  114175.79  294919.57  1   124266.9
1  0.0  1.0  0.0  1.0  0.0  0.0  1.0  153773.43  299737.29  2  111313.02
2  0.0  1.0  0.0  1.0  0.0  1.0  0.0  122782.75  303319.26  1  110352.25
3  1.0  0.0  1.0  0.0  1.0  0.0  0.0   96189.63  148001.11  0   71498.49
4  0.0  1.0  0.0  1.0  0.0  0.0  1.0   85047.44  205517.64  2   96479.51
5  0.0  1.0  0.0  1.0  0.0  1.0  0.0  156547.42  256512.92  1  132602.65
6  1.0  0.0  1.0  0.0  1.0  0.0  0.0  151377.59  443898.53  0  191792.06

3.Buat field baru yaitu Tax. dimana Tax = (profit + Marketing Spend + administration) * 5%

In [46]:
X=X.astype(int)
X

array([[     0,      1,      0,      1,      0,      1,      0, 114175,
        294919,      1, 124266],
       [     0,      1,      0,      1,      0,      0,      1, 153773,
        299737,      2, 111313],
       [     0,      1,      0,      1,      0,      1,      0, 122782,
        303319,      1, 110352],
       [     1,      0,      1,      0,      1,      0,      0,  96189,
        148001,      0,  71498],
       [     0,      1,      0,      1,      0,      0,      1,  85047,
        205517,      2,  96479],
       [     0,      1,      0,      1,      0,      1,      0, 156547,
        256512,      1, 132602],
       [     1,      0,      1,      0,      1,      0,      0, 151377,
        443898,      0, 191792]])

In [47]:
data_startups = pandas.read_csv('50_startups.csv')
data_startups = (data['Profit'] + data['Marketing Spend'] + data['Administration']) * 0.05

# Output data dengan field "Tax" baru
print(data)

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13             NaN        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10        NaN       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       

Jalankan standardScaler field-field tersebut

In [48]:
sc = StandardScaler()
X = sc.fit_transform(X)
X

array([[-0.63245553,  0.63245553, -0.63245553,  0.63245553, -0.63245553,
         1.15470054, -0.63245553, -0.42844583,  0.18736127,  0.        ,
         0.13011316],
       [-0.63245553,  0.63245553, -0.63245553,  0.63245553, -0.63245553,
        -0.8660254 ,  1.58113883,  1.0438059 ,  0.24351471,  1.32287566,
        -0.24369833],
       [-0.63245553,  0.63245553, -0.63245553,  0.63245553, -0.63245553,
         1.15470054, -0.63245553, -0.10843798,  0.28526266,  0.        ,
        -0.27143189],
       [ 1.58113883, -1.58113883,  1.58113883, -1.58113883,  1.58113883,
        -0.8660254 , -0.63245553, -1.09716444, -1.52495728, -1.32287566,
        -1.39272207],
       [-0.63245553,  0.63245553, -0.63245553,  0.63245553, -0.63245553,
        -0.8660254 ,  1.58113883, -1.51142346, -0.8546125 ,  1.32287566,
        -0.67179373],
       [-0.63245553,  0.63245553, -0.63245553,  0.63245553, -0.63245553,
         1.15470054, -0.63245553,  1.14694308, -0.2602695 ,  0.        ,
         0.370